spring:
  application:
    name: teektok
  datasource:
    # 数据库连接配置
    # 请确认数据库名 'teektok' 是否正确，如果还没创建数据库，请先去 MySQL 里 create database
    url: jdbc:mysql://exp.mysql.database.azure.com:3306/teektok?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: rinki
    # 请替换为你自己的 MySQL 密码
    password: "Song5118_"
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    # 服务器地址，请根据实际情况修改
    bootstrap-servers: 192.168.132.128:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # 可选：重试、acks 等生产环境再调
      retries: 3
      acks: all
  servlet:
    multipart:
      enabled: true
      # 单个文件的最大限制
      max-file-size: 500MB
      # 单次请求（包含多个文件）的总大小限制
      max-request-size: 500MB

  data:
    redis:
      host: 100.106.139.99
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    # 开启控制台 SQL 日志打印 (开发环境推荐开启，生产环境建议关闭)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启下划线转驼峰命名 (默认为 true，显式写出来更清晰)
    map-underscore-to-camel-case: true

# 自定义 Kafka Topic 配置
kafka:
  topic:
    behavior: short_video_behavior_topic # 可以在这里指定 Topic 的名称，需要匹配kafka的实际topic

#配置阿里云
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: teektok
    region: cn-beijing
